// Generated by egohygiene/identity. Do not edit.
export type IdentityTokenPath = "color.action.primary" | "color.brand.clean" | "color.brand.orchestration" | "color.brand.primary" | "color.canvas" | "color.inspection.canvas" | "color.inspection.text" | "color.text" | "motion.duration.reduced" | "motion.duration.standard" | "typography.body.family";
export declare const tokens: Readonly<Record<IdentityTokenPath, unknown>>;
export default tokens;
